ALTER TABLE users
ADD COLUMN first_name VARCHAR(255) NOT NULL,
ADD COLUMN last_name VARCHAR(255) NOT NULL;

ALTER TABLE authors ALTER COLUMN id TYPE BIGINT;
ALTER TABLE users ALTER COLUMN id TYPE BIGINT;
ALTER TABLE books ALTER COLUMN id TYPE BIGINT;

ALTER TABLE user_roles ALTER COLUMN user_id TYPE BIGINT;

ALTER TABLE book_authors ALTER COLUMN book_id TYPE BIGINT;
ALTER TABLE book_authors ALTER COLUMN author_id TYPE BIGINT;

ALTER TABLE book_genres ALTER COLUMN book_id TYPE BIGINT;

ALTER TABLE favorites ALTER COLUMN book_id TYPE BIGINT;
ALTER TABLE favorites ALTER COLUMN user_id TYPE BIGINT;